"""The Dirge of Cerberus world responder (UDP 55040).

The code lives in the `docworld` package beside this file, one module per
concern (docworld/__init__.py lists them). This module is the entry point
the container runs (`python docudp.py <flags>`; `--help` lists them) and a
compatibility facade: `import docudp` still resolves every name, reading or
writing, to the module that owns it, so tools and tests written against the
single-file layout keep working.
"""
import os
import sys
import types

# ONE COPY OF THIS MODULE. The container runs `python docudp.py`, so the
# running copy is `__main__`; a later `import docudp` would otherwise load a
# second copy.
if __name__ == "__main__":
    sys.modules.setdefault("docudp", sys.modules[__name__])

# the package and the sibling modules it imports (doc_*.py) sit beside this file
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from docworld import (  # noqa: E402,F401
    deps,
    framing,
    handshake,
    charrecords,
    worlddoor,
    worldchannel,
    lobbycmd,
    arenamaps,
    peerrecords,
    userlist,
    worldpose,
    tablerecords,
    tableverbs,
    questlist,
    advertise,
    gamemsg,
    battleroom,
    teamdist,
    briefingroom,
    arenadata,
    p2pbattle,
    fielditems,
    cli,
    worldserver,
)
from docworld.worldserver import main  # noqa: E402

# Which docworld module owns each top-level name of the old docudp.py.
_OWNERS = {
    'ARENA_NO_SPAWN': 'arenamaps',
    'ARENA_NO_ZONE': 'arenamaps',
    'ARENA_OK': 'arenamaps',
    'ARENA_TABLE_PATH': 'arenadata',
    'BASE_GIMMICKS': 'arenadata',
    'BASE_GIMMICKS_DEFAULT': 'arenadata',
    'BASE_OCCUPY_RADIUS': 'arenadata',
    'BASE_OCCUPY_S': 'arenadata',
    'BASE_POSE_FRESH_S': 'arenadata',
    'BASE_POSITIONS': 'arenadata',
    'BASE_REPORT_COUNT_OFF': 'arenadata',
    'BASE_REPORT_LEN': 'arenadata',
    'BASE_REPORT_OFF': 'arenadata',
    'BASE_TYPE_TEAM': 'arenadata',
    'BATTLETABLE_ANSWER_SEL': 'tablerecords',
    'BATTLETABLE_LIST_ANS': 'tablerecords',
    'BATTLETABLE_LIST_REQ': 'tablerecords',
    'BATTLETABLE_REC_OFF': 'tablerecords',
    'BODY_OFF': 'framing',
    'BT_FLAG_BEGINNER': 'tablerecords',
    'BT_FLAG_CUSTOM_RESTRICT': 'tablerecords',
    'BT_FLAG_FRIENDLY_FIRE': 'tablerecords',
    'BT_FLAG_HAS_RESTRICT': 'tablerecords',
    'BT_FLAG_INDIVIDUAL': 'tablerecords',
    'BT_FLAG_ITEM_RESTRICT': 'tablerecords',
    'BT_FLAG_KO_LIMIT': 'tablerecords',
    'BT_FLAG_MAX_RP': 'tablerecords',
    'BT_FLAG_MIN_RP': 'tablerecords',
    'BT_FLAG_MISSION': 'tablerecords',
    'BT_FLAG_NOVICE': 'tablerecords',
    'BT_FLAG_NPC': 'tablerecords',
    'BT_FLAG_PASSWORD': 'tablerecords',
    'BT_FLAG_RANDOM_TEAMS': 'tablerecords',
    'BT_FLAG_SOLO': 'tablerecords',
    'BT_FLAG_UNIT': 'tablerecords',
    'BT_JOIN_REQS': 'tableverbs',
    'BT_MAPS': 'tablerecords',
    'BT_MAP_ZONES_DEFAULT': 'arenamaps',
    'BT_MAX_MEMBERS': 'tableverbs',
    'BT_MEMBERS_OFF': 'tableverbs',
    'BT_MODE_NAMES': 'tablerecords',
    'BT_OFF_BASE_HP': 'tablerecords',
    'BT_OFF_BRIEFING': 'tablerecords',
    'BT_OFF_CAPSULES': 'tablerecords',
    'BT_OFF_COMMENT': 'tablerecords',
    'BT_OFF_CUR': 'tablerecords',
    'BT_OFF_FLAGS': 'tablerecords',
    'BT_OFF_GS_IP': 'tableverbs',
    'BT_OFF_GS_PORT': 'tableverbs',
    'BT_OFF_ID': 'tablerecords',
    'BT_OFF_KO_LIMIT': 'tablerecords',
    'BT_OFF_LEADER': 'tablerecords',
    'BT_OFF_MAP': 'tablerecords',
    'BT_OFF_MAX': 'tablerecords',
    'BT_OFF_MAX_RP': 'tablerecords',
    'BT_OFF_MIN_RP': 'tablerecords',
    'BT_OFF_MISSION': 'tablerecords',
    'BT_OFF_MODE': 'tablerecords',
    'BT_OFF_NIBBLES': 'tablerecords',
    'BT_OFF_PENALTY': 'tablerecords',
    'BT_OFF_PW_REC': 'tablerecords',
    'BT_OFF_RESTRICT': 'tablerecords',
    'BT_OFF_SITUATION': 'tablerecords',
    'BT_OFF_STATE': 'tablerecords',
    'BT_OFF_TARGET': 'tablerecords',
    'BT_OFF_TIME': 'tablerecords',
    'BT_OFF_UNK108': 'tablerecords',
    'BT_OFF_UNK111': 'tablerecords',
    'BT_OFF_UNK114': 'tablerecords',
    'BT_OFF_UNK116': 'tablerecords',
    'BT_OFF_UNK16': 'tablerecords',
    'BT_OFF_UNK22': 'tablerecords',
    'BT_OFF_UNK31': 'tablerecords',
    'BT_OFF_UNK32': 'tablerecords',
    'BT_OFF_UNK34': 'tablerecords',
    'BT_PASSWORD_OFF': 'tableverbs',
    'BT_REC_LEN': 'tablerecords',
    'BT_REFUSE_RP': 'battleroom',
    'BT_REQ_CANCEL': 'tableverbs',
    'BT_REQ_CONFIG': 'tableverbs',
    'BT_REQ_CREATE': 'tableverbs',
    'BT_REQ_DISSOLVE': 'tableverbs',
    'BT_REQ_INVITE': 'tableverbs',
    'BT_REQ_JOIN': 'tableverbs',
    'BT_REQ_JOIN_PW': 'tableverbs',
    'BT_REQ_PREPARE': 'tableverbs',
    'BT_REQ_REC_OFF': 'tableverbs',
    'BT_REQ_RESERVE': 'tableverbs',
    'BT_REQ_RESERVE_PW': 'tableverbs',
    'BT_REQ_UPDATE': 'tableverbs',
    'BT_RESERVATION_CLEAR_SEL': 'tableverbs',
    'BT_VERB_REQS': 'tableverbs',
    'BURST_GAP': 'worldserver',
    'BattleRoom': 'battleroom',
    'BattleRules': 'battleroom',
    'BattletableStore': 'tableverbs',
    'CAPSULE_HOLDERS': 'fielditems',
    'CAPSULE_HOLD_S': 'fielditems',
    'CAPSULE_RING': 'fielditems',
    'CARRIER_DROP_S': 'fielditems',
    'CHARA_ID_MEMBER_OFF': 'charrecords',
    'CHARA_MAX_RECORDS': 'charrecords',
    'CHARA_REC_OFF': 'charrecords',
    'CKSUM_OFF': 'framing',
    'CONTROLLER_NPCS': 'arenadata',
    'ENTRANCE_UID_OFF': 'worldpose',
    'FIELD_QUIET': 'fielditems',
    'FIELD_SLOTS': 'fielditems',
    'GS_ARM_MIN_BODY': 'gamemsg',
    'GS_ARM_MSG': 'gamemsg',
    'GS_BATTLE_GO_DEFAULT': 'briefingroom',
    'GS_BATTLE_OVER_SELECTOR': 'briefingroom',
    'GS_BATTLE_START_DEFAULT': 'briefingroom',
    'GS_DAMAGE_GATE_KIND': 'gamemsg',
    'GS_DAMAGE_GATE_KINDS': 'briefingroom',
    'GS_DOWN_KIND': 'gamemsg',
    'GS_ENDPOINT_SELECTOR': 'worldchannel',
    'GS_ENDPOINT_SELECTORS': 'worldchannel',
    'GS_INNER_TYPE': 'gamemsg',
    'GS_ITEM_USE_REQ': 'gamemsg',
    'GS_KEEPALIVE_MSG': 'gamemsg',
    'GS_KILL_EVENT': 'gamemsg',
    'GS_KILL_REQ': 'gamemsg',
    'GS_LEAVE_BRIEFING': 'gamemsg',
    'GS_MAGIC_ANS': 'gamemsg',
    'GS_MAGIC_REQ': 'gamemsg',
    'GS_MP_KIND': 'gamemsg',
    'GS_MSG_MAX': 'gamemsg',
    'GS_NOTIFY_KIND_LIMIT': 'briefingroom',
    'GS_NOTIFY_MSG': 'gamemsg',
    'GS_NOTIFY_NAMES': 'gamemsg',
    'GS_PLAYER_LEFT_KIND': 'gamemsg',
    'GS_READY_COUNT_OFF': 'gamemsg',
    'GS_READY_KIND_OFF': 'gamemsg',
    'GS_READY_ROSTER_OFF': 'gamemsg',
    'GS_READY_ROSTER_STRIDE': 'gamemsg',
    'GS_READY_SELECTOR': 'worldchannel',
    'GS_READY_SESSION_OFF': 'gamemsg',
    'GS_REQ_ANSWERS': 'gamemsg',
    'GS_REQ_NAMES': 'gamemsg',
    'GS_RESPAWN_KIND': 'gamemsg',
    'GS_RESTART_POS_KIND': 'gamemsg',
    'GS_REVIVE_KIND': 'gamemsg',
    'GS_REVIVE_REQ': 'gamemsg',
    'GS_SETUP_LEN': 'gamemsg',
    'GS_SPAWN_MAP_OFF': 'gamemsg',
    'GS_SPAWN_ZONE_OFF': 'gamemsg',
    'GS_TEAM_NONE': 'gamemsg',
    'GS_TEAM_SLOTS': 'gamemsg',
    'HDR_LEN': 'framing',
    'LEADER_TAG': 'battleroom',
    'LIST148_ANS': 'questlist',
    'LIST148_REQ': 'questlist',
    'LOBBY_CMD_APPOINT': 'lobbycmd',
    'LOBBY_CMD_CLOCK': 'lobbycmd',
    'LOBBY_CMD_KICK': 'lobbycmd',
    'LOBBY_CMD_PLAYTIME': 'lobbycmd',
    'LOBBY_CMD_QUEST': 'lobbycmd',
    'LOBBY_CMD_QUEST_INFO': 'lobbycmd',
    'LOBBY_CMD_RETURN': 'lobbycmd',
    'LOBBY_CMD_SELECTOR_ANS': 'lobbycmd',
    'LOBBY_CMD_SELECTOR_REQ': 'lobbycmd',
    'LOBBY_CMD_START': 'lobbycmd',
    'LOBBY_MAP_HIDDEN': 'arenamaps',
    'LOBBY_MAP_HOLES': 'arenamaps',
    'LOBBY_MAP_MASK': 'arenamaps',
    'LOBBY_MAP_MASK_ALL': 'arenamaps',
    'LOBBY_MAP_MASK_OFF': 'arenamaps',
    'LOBBY_MAP_NAMES': 'arenamaps',
    'LOBBY_ZONE': 'arenamaps',
    'LOBBY_ZONE_OFF': 'arenamaps',
    'MAKO_CAPSULE': 'fielditems',
    'MISSION_CTL_CHECK_S': 'gamemsg',
    'MISSION_CTL_GAP_S': 'gamemsg',
    'MISSION_CTL_TRIES': 'gamemsg',
    'MISSION_ROW_OPEN': 'questlist',
    'MISSION_SPAWNS': 'arenadata',
    'MODE_OFF': 'framing',
    'P2P_BATTLE_TYPES': 'p2pbattle',
    'P2P_DAMAGE': 'p2pbattle',
    'P2P_DAMAGE_STRIDE': 'p2pbattle',
    'P2P_DROP': 'p2pbattle',
    'P2P_MP_POINT': 'p2pbattle',
    'P2P_NAMES': 'p2pbattle',
    'P2P_PAYLOAD_LEN_OFF': 'p2pbattle',
    'P2P_PAYLOAD_OFF': 'p2pbattle',
    'P2P_PICKUP': 'p2pbattle',
    'P2P_SENDER_OFF': 'p2pbattle',
    'P2P_SERVER_TYPES': 'p2pbattle',
    'P2P_SHOT': 'p2pbattle',
    'P2P_TARGET_OFF': 'p2pbattle',
    'PEER_FLAGS_OFF': 'peerrecords',
    'PEER_IP_OFF': 'peerrecords',
    'PEER_NAME_LEN': 'peerrecords',
    'PEER_NAME_OFF': 'peerrecords',
    'PEER_PORT_OFF': 'peerrecords',
    'PEER_POS_LEN': 'worldpose',
    'PEER_PROBE': 'peerrecords',
    'PEER_RANK_OFF': 'peerrecords',
    'PEER_REC_LEN': 'peerrecords',
    'PEER_RELAY_FLAG': 'worldpose',
    'PEER_SELECTOR_ANS': 'peerrecords',
    'PEER_SELECTOR_REQ': 'peerrecords',
    'PEER_ZONE_OFF': 'peerrecords',
    'PORT': 'framing',
    'PROBE_SLOTS': 'charrecords',
    'QUEST_DETAIL_MAP_OFF': 'questlist',
    'QUEST_LIST_REQ': 'questlist',
    'SELECTOR_NAMES': 'worldchannel',
    'SPAWN_OFF_DIR_X': 'arenamaps',
    'SPAWN_OFF_DIR_Y': 'arenamaps',
    'SPAWN_OFF_DIR_Z': 'arenamaps',
    'SPAWN_OFF_INDEX': 'arenamaps',
    'SPAWN_OFF_X': 'arenamaps',
    'SPAWN_OFF_Y': 'arenamaps',
    'SPAWN_OFF_Z': 'arenamaps',
    'SPAWN_PRESETS': 'arenamaps',
    'SPAWN_ROOM': 'arenamaps',
    'SPAWN_Y_BIAS': 'arenamaps',
    'SWEEP': 'worldserver',
    'TEAM_STARTS': 'arenadata',
    'TEAM_START_STEP': 'arenadata',
    'USER_SELECTOR_ANS': 'userlist',
    'USER_SELECTOR_REQ': 'userlist',
    'USER_SELECTOR_REQS': 'userlist',
    'WORLD_DOOR_UID_OFF': 'worldpose',
    'WORLD_REC_LEN': 'worldpose',
    'WORLD_SPAWN_SELECTOR_ANS': 'arenamaps',
    'WORLD_UPDATE_TYPE': 'worldpose',
    'ZONE_PIECES_DEFAULT': 'arenamaps',
    'ZONE_SPAWNS_DEFAULT': 'arenamaps',
    '_KELCRYPT': 'deps',
    '_RFC1918_NETS': 'advertise',
    '_ip_or_none': 'advertise',
    '_ipaddress': 'deps',
    '_is_rfc1918': 'advertise',
    '_user_rec_fields': 'peerrecords',
    '_week_start_arg': 'cli',
    'argparse': 'deps',
    'base_gimmicks': 'arenadata',
    'base_hp_payload': 'arenadata',
    'base_objects_payload': 'arenadata',
    'base_occupy_tick': 'arenadata',
    'base_report': 'arenadata',
    'base_spots': 'arenadata',
    'battle_bmap': 'arenamaps',
    'battle_map_arena': 'arenamaps',
    'battle_rules_from_record': 'battleroom',
    'battletable_verb': 'tableverbs',
    'bt_start_targets': 'teamdist',
    'build_battletable_list': 'tablerecords',
    'build_battletable_probe': 'tablerecords',
    'build_battletable_record': 'tablerecords',
    'build_battletable_verb_answer': 'tableverbs',
    'build_chara_record': 'charrecords',
    'build_charamake_answer': 'charrecords',
    'build_frag3': 'handshake',
    'build_gs_add_chara': 'gamemsg',
    'build_gs_distribution': 'gamemsg',
    'build_gs_down': 'gamemsg',
    'build_gs_kill_event': 'gamemsg',
    'build_gs_message': 'gamemsg',
    'build_gs_mp_push': 'gamemsg',
    'build_gs_notify': 'gamemsg',
    'build_gs_spawn': 'gamemsg',
    'build_gs_stats': 'gamemsg',
    'build_gs_team_leave': 'gamemsg',
    'build_gs_team_list': 'gamemsg',
    'build_gs_team_set': 'gamemsg',
    'build_item_use_answer': 'gamemsg',
    'build_list148_body': 'questlist',
    'build_lobby_advance': 'handshake',
    'build_magic_answer': 'gamemsg',
    'build_parser': 'cli',
    'build_peer_answer': 'peerrecords',
    'build_peer_record': 'peerrecords',
    'build_peer_relay': 'worldpose',
    'build_probe_record': 'charrecords',
    'build_quest_list_body': 'questlist',
    'build_reliable_ack': 'framing',
    'build_reply': 'framing',
    'build_reserve_echo': 'tableverbs',
    'build_srv_entry': 'handshake',
    'build_used_record': 'charrecords',
    'build_user_list_answer': 'userlist',
    'build_world_answer': 'worlddoor',
    'build_world_update': 'worldpose',
    'capsule_count': 'fielditems',
    'capsule_drop': 'fielditems',
    'capsule_hold': 'fielditems',
    'capsule_hold_done': 'fielditems',
    'capsule_mission_check': 'fielditems',
    'capsule_pickup': 'fielditems',
    'capsule_ring': 'fielditems',
    'capsule_scoreboard_payload': 'fielditems',
    'chara_id_for': 'charrecords',
    'chara_id_of': 'charrecords',
    'cksum': 'framing',
    'datetime': 'deps',
    'describe': 'framing',
    'describe_inner': 'framing',
    'describe_map_mask': 'arenamaps',
    'doc_charastore': 'deps',
    'doc_chat': 'deps',
    'doc_field': 'deps',
    'doc_gear': 'deps',
    'doc_items': 'deps',
    'doc_kelcrypt': 'deps',
    'doc_magic': 'deps',
    'doc_missions': 'deps',
    'doc_novice': 'deps',
    'doc_npc': 'deps',
    'doc_npc_spawn': 'deps',
    'doc_npcquests': 'deps',
    'doc_playtime': 'deps',
    'doc_rank': 'deps',
    'doc_shop': 'deps',
    'doc_stats': 'deps',
    'doc_trade': 'deps',
    'doc_unit': 'deps',
    'early_uid': 'worldpose',
    'field_item_payload': 'fielditems',
    'gs_auto_teams': 'teamdist',
    'gs_battle_sequence': 'briefingroom',
    'gs_dist_due': 'teamdist',
    'gs_kill_report': 'gamemsg',
    'gs_ready_roster': 'briefingroom',
    'gs_real_distribution': 'teamdist',
    'gs_real_ready': 'teamdist',
    'gs_rebalance_teams': 'teamdist',
    'gs_request_type': 'gamemsg',
    'gs_solo_distribution': 'teamdist',
    'hexdump': 'framing',
    'host_for': 'advertise',
    'ingame_pose': 'worldpose',
    'ingame_uid': 'worldpose',
    'load_arena_table': 'arenadata',
    'load_mission_spawns': 'arenadata',
    'lobby_clock_value': 'lobbycmd',
    'lobby_cmd_id': 'lobbycmd',
    'main': 'worldserver',
    'math': 'deps',
    'mission_npc_report': 'gamemsg',
    'now_ms': 'framing',
    'npc_controller_payload': 'arenadata',
    'os': 'deps',
    'p2p_battle_type': 'p2pbattle',
    'p2p_battle_type_mode4': 'p2pbattle',
    'p2p_damage_entries': 'p2pbattle',
    'p2p_drop': 'fielditems',
    'p2p_pickup_slot': 'fielditems',
    'p2p_record': 'p2pbattle',
    'p2p_server_type': 'p2pbattle',
    'p2p_server_type_mode4': 'p2pbattle',
    'packet_charid': 'worldchannel',
    'parse_battletable_spec': 'tablerecords',
    'parse_id_ranges': 'questlist',
    'parse_list148_spec': 'questlist',
    'parse_map_mask': 'arenamaps',
    'parse_map_zones': 'arenamaps',
    'parse_zone_pieces': 'arenamaps',
    'peer_miss_id': 'peerrecords',
    'peer_pos_id': 'worldpose',
    'quest_mission_record': 'briefingroom',
    'rec_for': 'advertise',
    'record_password': 'battleroom',
    'request_body': 'worldchannel',
    'rp_allowed': 'battleroom',
    'seal_world_body': 'worldchannel',
    'select': 'deps',
    'selector_name': 'worldchannel',
    'socket': 'deps',
    'struct': 'deps',
    'synth_p2p_inner': 'p2pbattle',
    'synth_peer_inner': 'p2pbattle',
    'sys': 'deps',
    'team_start': 'arenadata',
    'time': 'deps',
    'unit_teams': 'battleroom',
    'user_list_wanted_id': 'userlist',
    'world_reply_fields': 'worldchannel',
}
_MODULES = {
    'deps': deps,
    'framing': framing,
    'handshake': handshake,
    'charrecords': charrecords,
    'worlddoor': worlddoor,
    'worldchannel': worldchannel,
    'lobbycmd': lobbycmd,
    'arenamaps': arenamaps,
    'peerrecords': peerrecords,
    'userlist': userlist,
    'worldpose': worldpose,
    'tablerecords': tablerecords,
    'tableverbs': tableverbs,
    'questlist': questlist,
    'advertise': advertise,
    'gamemsg': gamemsg,
    'battleroom': battleroom,
    'teamdist': teamdist,
    'briefingroom': briefingroom,
    'arenadata': arenadata,
    'p2pbattle': p2pbattle,
    'fielditems': fielditems,
    'cli': cli,
    'worldserver': worldserver,
}


class _Facade(types.ModuleType):
    """`docudp.<name>` reads and writes go to the owning docworld module."""

    def __getattr__(self, name):
        mod = _OWNERS.get(name)
        if mod is None:
            raise AttributeError(f"module 'docudp' has no attribute {name!r}")
        return getattr(_MODULES[mod], name)

    def __setattr__(self, name, value):
        mod = _OWNERS.get(name)
        if mod is None:
            super().__setattr__(name, value)
            return
        setattr(_MODULES[mod], name, value)
        if mod == "deps":
            # an imported name is a copy in every module that imported it;
            # a patch has to reach each copy
            for other in _MODULES.values():
                if other is not deps and hasattr(other, name):
                    setattr(other, name, value)

    def __dir__(self):
        return sorted(set(super().__dir__()) | set(_OWNERS))


sys.modules[__name__].__class__ = _Facade


if __name__ == "__main__":
    try:
        sys.exit(main() or 0)
    except KeyboardInterrupt:
        print("\n[docudp] stopped")
